name: Release

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    release:
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        name: Release
        environment: release
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install npm dependencies
              run: npm ci
              env:
                  NODE_ENV: development

            # - name: Lint files
            #   run: npm run lint

            # - name: Typechecks
            #   run: npm run typecheck

            # - name: Prettier check
            #   run: npm run prettier:check

            - name: Build
              run: npm run build
              env:
                  NODE_ENV: production

            - name: Derive VITE_APP_VERSION from tag (strip leading 'v')
              uses: actions/github-script@v7
              with:
                  script: |
                      const ref = process.env.GITHUB_REF_NAME || '';
                      const ver = ref.startsWith('v') ? ref.slice(1) : ref;
                      core.exportVariable('VITE_APP_VERSION', ver);

            - name: Package and publish
              run: npm run package:publish
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    upload-templates:
        runs-on: ubuntu-latest
        name: Upload templates to release
        needs: release
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Upload template JSON files to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  files: |
                      src/static/document_未使用公务卡报销情况说明.json
                      src/static/template_国内差旅.json
