name: Release

permissions:
  contents: write

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    # create-release:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - uses: actions/checkout@v4
    #       - name: Create release
    #         uses: softprops/action-gh-release@v2
    #         with:
    #             tag_name: ${{ github.ref_name }}
    #             name: ${{ github.ref_name }}
    #             token: ${{ secrets.GITHUB_TOKEN }}
    #             draft: false
    #             prerelease: true

    release:
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        name: Release
        environment: release
        # needs: create-release
        steps:
            - name: Checkout current commit/branch/tag
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install npm dependencies
              run: npm ci
              env:
                  NODE_ENV: development

            # - name: Lint files
            #   run: npm run lint

            # - name: Typechecks
            #   run: npm run typecheck

            # - name: Prettier check
            #   run: npm run prettier:check

            - name: Derive VITE_APP_VERSION from tag (strip leading 'v')
              uses: actions/github-script@v7
              with:
                  script: |
                      const ref = process.env.GITHUB_REF_NAME || '';
                      const ver = ref.startsWith('v') ? ref.slice(1) : ref;
                      core.exportVariable('VITE_APP_VERSION', ver);

            - name: Build
              run: npm run build
              env:
                  NODE_ENV: production

            - name: Package and publish
              run: npm run package:publish
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    upload-templates:
        runs-on: ubuntu-latest
        name: Upload templates to release
        needs: release
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Upload template JSON files to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ github.ref_name }}
                  fail_on_unmatched_files: true
                  files: |
                      src/static/document_WHUH_reimbursement_without_corporate_card.json
                      src/static/template_WHUH_domestic_travel.json
